name: Bump Version
on:
  workflow_dispatch:
    inputs:
      version:
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Bump Version
        run: |
          export VERSION=${{ github.event.inputs.version }}
          make bump-version
      - name: Create PR
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Bump version
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: bump_version
          push-to-fork: minikube-bot/minikube-gui
          base: main
          delete-branch: true
          title: 'Bump version'
