name: Bump Version
on:
  workflow_dispatch:
    inputs:
      version:
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Bump Version
        run: |
          export VERSION=${{ github.event.inputs.version }}
          make bump-version
      - name: Create PR
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Bump version
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: bump_version
          push-to-fork: minikube-bot/minikube-gui
          base: main
          delete-branch: true
          title: 'Bump version'
