name: Build macOS
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: jurplel/install-qt-action@2d518188e746defd451af981c3c901f463d99e29
        with:
          cache: true
      - name: build
        run: |
          make build-macos
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: minikube-gui-macos
          path: ./minikube-gui-macos.dmg
